name: 'Verify code quality'

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer install
        uses: php-actions/composer@v6

      - name: Validate code style
        run: vendor/bin/php-cs-fixer fix --dry-run

      - name: Run static analysis
        run: vendor/bin/phpstan
